"""
Django settings for my_django_project.

Generated by 'django-admin startproject' using Django 4.0.
"""

import os
import secrets
import environ
from pathlib import Path

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "your-secret-key"
if not DEBUG:
    # rotating random secret key
    SECRET_KEY = secrets.token_hex()

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "app",  # Include your app here
    "django_gauth",
]

MIDDLEWARE = [
    "app.middleware.CacheControlStaticMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "my_django_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "my_django_project.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "app/static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# django-gauth settings
GOOGLE_CLIENT_ID = env('GOOGLE_CLIENT_ID')  # << set according to your oauth2 client
GOOGLE_CLIENT_SECRET = env('GOOGLE_CLIENT_SECRET')  # << set according to your oauth2 client
GOOGLE_AUTH_FINAL_REDIRECT_URL = None  # defaults to `<host>/gauth/`
CREDENTIALS_SESSION_KEY_NAME = "credentials"  # defaults to `credentials`
STATE_KEY_NAME = "oauth_state"  # defaults to `oauth_state`
SCOPE = [
    "https://www.googleapis.com/auth/userinfo.email",  # always preffered
    "https://www.googleapis.com/auth/userinfo.profile",  # always preffered
    "openid",  # always preffered
    "https://www.googleapis.com/auth/drive",  # based on your usage
]
os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "1"  # strictly for local-development only
GAUTH_LANDING_UI_CONFIG = '{"index": {"navbar": {"logo": "", "profile_picture_absence": "", "style": {"logo_background": "white", "background_color": "background-color: rgb(252 253 251 / var(--tw-bg-opacity, 1));", "text_color": "black", "border": "1px solid lightgray"}}, "status_bar": {"session_timer": {"style": {"color": "black"}}, "authenticate_button": {"style": {"background_color": "rgb(0 125 73/var(--tw-bg-opacity,1))", "text_color": "white"}}}}}'
