"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import environ  # pylint: disable=E0401

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

ENV = os.environ.get('ENV', 'local')
# Take environment variables from .env file
try:
    environ.Env.read_env(os.environ['ENV_PATH'])
    print('loaded environment : from ENV_PATH')
except Exception:
    env_file_name = '.env'  # pylint: disable=invalid-name
    if ENV == 'prod':
        env_file_suffix = '.prod'   # pylint: disable=invalid-name
    if ENV == 'test':
        env_file_suffix = '.test'   # pylint: disable=invalid-name
    else:
        env_file_suffix = ''    # pylint: disable=invalid-name
    env_file_name += env_file_suffix    # pylint: disable=invalid-name
    environ.Env.read_env(os.path.join(BASE_DIR, env_file_name))
    print(f'loaded environment : from BASE_DIR : `{env_file_name=}`')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c_k3p%xtt1zn%hzwnom^#98s28qlhpwslj6)arn59p2%!s+y%z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

AUTHENTICATION_BACKENDS = [
    "django_gauth.backends.GoogleAuthBackend",
    "django.contrib.auth.backends.ModelBackend",
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_gauth',
    'rest_framework',
    'api'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Directory where `collectstatic` gathers all static assets (admin, DRF
# browsable API, etc.) so that Nginx can serve them directly from a shared
# volume instead of routing static requests through gunicorn.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Gauth settings
# ==============
GOOGLE_CLIENT_ID= env("GOOGLE_CLIENT_ID")           # << set according to your oauth2 client
GOOGLE_CLIENT_SECRET= env("GOOGLE_CLIENT_SECRET")   # << set according to your oauth2 client
GOOGLE_AUTH_FINAL_REDIRECT_URL= None        # defaults to `<host>/gauth/`
CREDENTIALS_SESSION_KEY_NAME= "credentials" # defaults to `credentials`
STATE_KEY_NAME= "oauth_state"               # defaults to `oauth_state`
SCOPE= [
    "https://www.googleapis.com/auth/userinfo.email"    # always preffered
    ,"https://www.googleapis.com/auth/userinfo.profile" # always preffered
    ,"openid"                                           # always preffered
    ,"https://www.googleapis.com/auth/drive"            # based on your usage
]
os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'         # strictly for local-development only
GOOGLE_SESSION_AUTO_REFRESH=False
GOOGLE_SESSION_MAX_AGE=60*30
# GOOGLE_SESSION_IDLE_TIMEOUT = 60
GOOGLE_USER_INTEGRATION = True